[package]
name = "folder_encryptor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chacha20 = "0.9.0"
rand = "0.8.5"
rand_core = "0.6.4"
rpassword = "7.2.0"
rust-argon2 = "1.0.0"
